import React from 'react';
import { TrendingUp, BarChart3, Users, Zap, CheckCircle2, ArrowUpRight } from 'lucide-react';

export function PortalPerformanceTab({ stats = {}, client = {} }) {
  return (
    <div className="portal-performance-pane">
      {/* Overview Cards */}
      <div className="perf-summary-card">
        <div className="perf-header-row">
          <div className="perf-icon-badge">
            <TrendingUp size={18} />
          </div>
          <div>
            <h3 className="section-title">Monthly Marketing Performance & Attribution</h3>
            <p className="section-desc">Aggregate organic reach and paid campaign ROAS generated by PulseAI</p>
          </div>
        </div>

        <div className="perf-metrics-row-three">
          <div className="perf-metric-block">
            <span className="p-lbl">Total Audience Reach</span>
            <strong className="p-val">{stats.reach || '94.2K'}</strong>
            <span className="p-delta positive">+14.2% Growth vs Last Month</span>
          </div>

          <div className="perf-metric-block">
            <span className="p-lbl">Average Yield ROAS</span>
            <strong className="p-val text-success">{stats.roas || '5.56x'}</strong>
            <span className="p-delta positive">Top Tier Category Performance</span>
          </div>

          <div className="perf-metric-block">
            <span className="p-lbl">Attributed Conversions</span>
            <strong className="p-val text-cyan">{stats.leads || '184 Leads'}</strong>
            <span className="p-delta positive">Qualified Customer Inquiries</span>
          </div>
        </div>
      </div>

      {/* Channel Breakdown Table */}
      <div className="perf-breakdown-card">
        <h4 className="card-sub-title">Managed Social Channel Breakdown</h4>
        <table className="saas-table client-perf-table">
          <thead>
            <tr>
              <th>Channel Platform</th>
              <th>Published Assets</th>
              <th>Monthly Engagements</th>
              <th>Audience Growth</th>
              <th>Health Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Instagram Business</strong></td>
              <td>12 Reels & Posts</td>
              <td>14,200 Interactions</td>
              <td><span className="text-success">+14.2%</span></td>
              <td><span className="status-pill-badge connected">Active & Optimized</span></td>
            </tr>
            <tr>
              <td><strong>Facebook Pages</strong></td>
              <td>8 Posts & Stories</td>
              <td>6,800 Interactions</td>
              <td><span className="text-success">+6.8%</span></td>
              <td><span className="status-pill-badge connected">Active & Optimized</span></td>
            </tr>
            <tr>
              <td><strong>LinkedIn Company Page</strong></td>
              <td>6 Thought Leadership Posts</td>
              <td>2,400 Interactions</td>
              <td><span className="text-success">+8.4%</span></td>
              <td><span className="status-pill-badge connected">Active & Optimized</span></td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Account Manager Contact Banner */}
      <div className="account-manager-banner">
        <div className="am-left">
          <span className="am-label">Assigned Agency Director</span>
          <strong className="am-name">{client.accountManager || 'Alex Morgan'}</strong>
          <span className="am-email">Questions or strategy requests? Email {client.contactEmail || 'support@agency.ai'}</span>
        </div>
      </div>
    </div>
  );
}

export default PortalPerformanceTab;
